/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tony.goshredding.ui;

import com.tony.goshredding.util.GoHelper;
import com.tony.goshredding.vo.EventVO;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.border.BevelBorder;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author syp386
 */
public class EventCellPanel extends javax.swing.JPanel {

    /**
     * Creates new form EventItemPanel
     */
    private EventVO eventObj;
    public void setSelectedState(boolean bSelected){
      if (bSelected) {
            jPanel1.setBackground(new java.awt.Color(218, 227, 243));
        } else {
            jPanel1.setBackground(new java.awt.Color(239, 246, 254));
        }
    }
    public EventCellPanel(EventVO eventVO) {
        initComponents();
      
        this.eventObj = eventVO;
        eventNameLbl.setText(eventObj.eventName);
        eventDateLbl.setText(eventObj.eventDate);
        String time = null;
        String timeSlot = null;
        if(eventObj.eventTime != null){
        String[] timeArray = eventObj.eventTime.split(":");
        int hours = Integer.parseInt(timeArray[0]);
        String minutes = timeArray[1];
        if (hours >= 0 && hours <= 11) {
            time = hours + ":" + minutes;
            timeSlot = "AM";
        } else if (hours >= 12 && hours <= 23) {
            time = (hours - 12) + ":" + minutes;
            timeSlot = "PM";
        }
        timeLbl.setText(time+" "+timeSlot);
        }
        if (eventObj.eventPicName != null && eventObj.eventPicName.length() > 0) {
            try {
                GoHelper.downloadImage(eventObj.eventPicName);
                File directory = new File("");
                String filePath = directory.getCanonicalPath() + "/images/" + eventObj.eventPicName;
                File targetFile = new File(filePath);
                Image image = new ImageIcon(targetFile.getAbsolutePath()).getImage();
                image = image.getScaledInstance(104, 60, Image.SCALE_SMOOTH);
                imageLbl.setIcon(new ImageIcon(image));
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
        if (eventObj.eventTypePicName != null && eventObj.eventTypePicName.length() > 0) {

            try {

                Image image2 = new ImageIcon(getClass().getResource("/com/tony/goshredding/files/" + eventObj.eventTypePicName)).getImage();
                image2 = image2.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
                eventTypeLbl.setIcon(new ImageIcon(image2));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eventNameLbl = new javax.swing.JLabel();
        eventDateLbl = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        imageLbl = new javax.swing.JLabel();
        eventTypeLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(239, 246, 254));
        setPreferredSize(new java.awt.Dimension(810, 75));

        jPanel1.setBackground(new java.awt.Color(239, 246, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(810, 75));
        jPanel1.setLayout(null);

        eventNameLbl.setFont(new java.awt.Font("Lucida Grande", 0, 19)); // NOI18N
        eventNameLbl.setText("Event name");
        jPanel1.add(eventNameLbl);
        eventNameLbl.setBounds(8, 14, 370, 23);

        eventDateLbl.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        eventDateLbl.setMaximumSize(new java.awt.Dimension(110, 20));
        eventDateLbl.setMinimumSize(new java.awt.Dimension(110, 20));
        jPanel1.add(eventDateLbl);
        eventDateLbl.setBounds(8, 43, 110, 20);

        timeLbl.setFont(new java.awt.Font("Lucida Grande", 0, 17)); // NOI18N
        timeLbl.setMaximumSize(new java.awt.Dimension(90, 21));
        timeLbl.setMinimumSize(new java.awt.Dimension(90, 21));
        jPanel1.add(timeLbl);
        timeLbl.setBounds(400, 30, 90, 20);
        jPanel1.add(imageLbl);
        imageLbl.setBounds(528, 8, 104, 60);
        jPanel1.add(eventTypeLbl);
        eventTypeLbl.setBounds(690, 13, 50, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eventDateLbl;
    private javax.swing.JLabel eventNameLbl;
    private javax.swing.JLabel eventTypeLbl;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel timeLbl;
    // End of variables declaration//GEN-END:variables

}
